/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.knowarth.security.service.base;

import aQute.bnd.annotation.ProviderType;

import com.knowarth.security.model.SecureLogin;
import com.knowarth.security.service.SecureLoginLocalService;
import com.knowarth.security.service.persistence.SecureLoginFinder;
import com.knowarth.security.service.persistence.SecureLoginPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the secure login local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.knowarth.security.service.impl.SecureLoginLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.knowarth.security.service.impl.SecureLoginLocalServiceImpl
 * @see com.knowarth.security.service.SecureLoginLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class SecureLoginLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements SecureLoginLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.knowarth.security.service.SecureLoginLocalServiceUtil} to access the secure login local service.
	 */

	/**
	 * Adds the secure login to the database. Also notifies the appropriate model listeners.
	 *
	 * @param secureLogin the secure login
	 * @return the secure login that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SecureLogin addSecureLogin(SecureLogin secureLogin) {
		secureLogin.setNew(true);

		return secureLoginPersistence.update(secureLogin);
	}

	/**
	 * Creates a new secure login with the primary key. Does not add the secure login to the database.
	 *
	 * @param secureLoginId the primary key for the new secure login
	 * @return the new secure login
	 */
	@Override
	public SecureLogin createSecureLogin(long secureLoginId) {
		return secureLoginPersistence.create(secureLoginId);
	}

	/**
	 * Deletes the secure login with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param secureLoginId the primary key of the secure login
	 * @return the secure login that was removed
	 * @throws PortalException if a secure login with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SecureLogin deleteSecureLogin(long secureLoginId)
		throws PortalException {
		return secureLoginPersistence.remove(secureLoginId);
	}

	/**
	 * Deletes the secure login from the database. Also notifies the appropriate model listeners.
	 *
	 * @param secureLogin the secure login
	 * @return the secure login that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SecureLogin deleteSecureLogin(SecureLogin secureLogin) {
		return secureLoginPersistence.remove(secureLogin);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(SecureLogin.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return secureLoginPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.knowarth.security.model.impl.SecureLoginModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return secureLoginPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.knowarth.security.model.impl.SecureLoginModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return secureLoginPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return secureLoginPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return secureLoginPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public SecureLogin fetchSecureLogin(long secureLoginId) {
		return secureLoginPersistence.fetchByPrimaryKey(secureLoginId);
	}

	/**
	 * Returns the secure login with the primary key.
	 *
	 * @param secureLoginId the primary key of the secure login
	 * @return the secure login
	 * @throws PortalException if a secure login with the primary key could not be found
	 */
	@Override
	public SecureLogin getSecureLogin(long secureLoginId)
		throws PortalException {
		return secureLoginPersistence.findByPrimaryKey(secureLoginId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(secureLoginLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SecureLogin.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("secureLoginId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(secureLoginLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(SecureLogin.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"secureLoginId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(secureLoginLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SecureLogin.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("secureLoginId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return secureLoginLocalService.deleteSecureLogin((SecureLogin)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return secureLoginPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the secure logins.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.knowarth.security.model.impl.SecureLoginModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of secure logins
	 * @param end the upper bound of the range of secure logins (not inclusive)
	 * @return the range of secure logins
	 */
	@Override
	public List<SecureLogin> getSecureLogins(int start, int end) {
		return secureLoginPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of secure logins.
	 *
	 * @return the number of secure logins
	 */
	@Override
	public int getSecureLoginsCount() {
		return secureLoginPersistence.countAll();
	}

	/**
	 * Updates the secure login in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param secureLogin the secure login
	 * @return the secure login that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SecureLogin updateSecureLogin(SecureLogin secureLogin) {
		return secureLoginPersistence.update(secureLogin);
	}

	/**
	 * Returns the secure login local service.
	 *
	 * @return the secure login local service
	 */
	public SecureLoginLocalService getSecureLoginLocalService() {
		return secureLoginLocalService;
	}

	/**
	 * Sets the secure login local service.
	 *
	 * @param secureLoginLocalService the secure login local service
	 */
	public void setSecureLoginLocalService(
		SecureLoginLocalService secureLoginLocalService) {
		this.secureLoginLocalService = secureLoginLocalService;
	}

	/**
	 * Returns the secure login persistence.
	 *
	 * @return the secure login persistence
	 */
	public SecureLoginPersistence getSecureLoginPersistence() {
		return secureLoginPersistence;
	}

	/**
	 * Sets the secure login persistence.
	 *
	 * @param secureLoginPersistence the secure login persistence
	 */
	public void setSecureLoginPersistence(
		SecureLoginPersistence secureLoginPersistence) {
		this.secureLoginPersistence = secureLoginPersistence;
	}

	/**
	 * Returns the secure login finder.
	 *
	 * @return the secure login finder
	 */
	public SecureLoginFinder getSecureLoginFinder() {
		return secureLoginFinder;
	}

	/**
	 * Sets the secure login finder.
	 *
	 * @param secureLoginFinder the secure login finder
	 */
	public void setSecureLoginFinder(SecureLoginFinder secureLoginFinder) {
		this.secureLoginFinder = secureLoginFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.knowarth.security.model.SecureLogin",
			secureLoginLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.knowarth.security.model.SecureLogin");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SecureLoginLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SecureLogin.class;
	}

	protected String getModelClassName() {
		return SecureLogin.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = secureLoginPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = SecureLoginLocalService.class)
	protected SecureLoginLocalService secureLoginLocalService;
	@BeanReference(type = SecureLoginPersistence.class)
	protected SecureLoginPersistence secureLoginPersistence;
	@BeanReference(type = SecureLoginFinder.class)
	protected SecureLoginFinder secureLoginFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}