/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.knowarth.security.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SecureLogin service. Represents a row in the &quot;SLS_SecureLogin&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.knowarth.security.model.impl.SecureLoginModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.knowarth.security.model.impl.SecureLoginImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SecureLogin
 * @see com.knowarth.security.model.impl.SecureLoginImpl
 * @see com.knowarth.security.model.impl.SecureLoginModelImpl
 * @generated
 */
@ProviderType
public interface SecureLoginModel extends BaseModel<SecureLogin> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a secure login model instance should use the {@link SecureLogin} interface instead.
	 */

	/**
	 * Returns the primary key of this secure login.
	 *
	 * @return the primary key of this secure login
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this secure login.
	 *
	 * @param primaryKey the primary key of this secure login
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the secure login ID of this secure login.
	 *
	 * @return the secure login ID of this secure login
	 */
	public long getSecureLoginId();

	/**
	 * Sets the secure login ID of this secure login.
	 *
	 * @param secureLoginId the secure login ID of this secure login
	 */
	public void setSecureLoginId(long secureLoginId);

	/**
	 * Returns the user ID of this secure login.
	 *
	 * @return the user ID of this secure login
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this secure login.
	 *
	 * @param userId the user ID of this secure login
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this secure login.
	 *
	 * @return the user uuid of this secure login
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this secure login.
	 *
	 * @param userUuid the user uuid of this secure login
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the registration key of this secure login.
	 *
	 * @return the registration key of this secure login
	 */
	@AutoEscape
	public String getRegistrationKey();

	/**
	 * Sets the registration key of this secure login.
	 *
	 * @param registrationKey the registration key of this secure login
	 */
	public void setRegistrationKey(String registrationKey);

	/**
	 * Returns the encode token of this secure login.
	 *
	 * @return the encode token of this secure login
	 */
	@AutoEscape
	public String getEncodeToken();

	/**
	 * Sets the encode token of this secure login.
	 *
	 * @param encodeToken the encode token of this secure login
	 */
	public void setEncodeToken(String encodeToken);

	/**
	 * Returns the encode token date of this secure login.
	 *
	 * @return the encode token date of this secure login
	 */
	public Date getEncodeTokenDate();

	/**
	 * Sets the encode token date of this secure login.
	 *
	 * @param encodeTokenDate the encode token date of this secure login
	 */
	public void setEncodeTokenDate(Date encodeTokenDate);

	/**
	 * Returns the qr code token of this secure login.
	 *
	 * @return the qr code token of this secure login
	 */
	@AutoEscape
	public String getQrCodeToken();

	/**
	 * Sets the qr code token of this secure login.
	 *
	 * @param qrCodeToken the qr code token of this secure login
	 */
	public void setQrCodeToken(String qrCodeToken);

	/**
	 * Returns the qr code token date of this secure login.
	 *
	 * @return the qr code token date of this secure login
	 */
	public Date getQrCodeTokenDate();

	/**
	 * Sets the qr code token date of this secure login.
	 *
	 * @param qrCodeTokenDate the qr code token date of this secure login
	 */
	public void setQrCodeTokenDate(Date qrCodeTokenDate);

	/**
	 * Returns the token validated of this secure login.
	 *
	 * @return the token validated of this secure login
	 */
	@AutoEscape
	public String getTokenValidated();

	/**
	 * Sets the token validated of this secure login.
	 *
	 * @param tokenValidated the token validated of this secure login
	 */
	public void setTokenValidated(String tokenValidated);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SecureLogin secureLogin);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SecureLogin> toCacheModel();

	@Override
	public SecureLogin toEscapedModel();

	@Override
	public SecureLogin toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}